spring:
  application:
    name: event-gateway
  mvc:
    problemdetails:
      enabled: true
  datasource:
    url: jdbc:h2:mem:gateway;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always
