spring:
  application:
    name: account-service
  datasource:
    url: jdbc:h2:mem:account;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  mvc:
    problemdetails:
      enabled: true
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always
